# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'inventory_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17inventory_service.proto\x12\tinventory\"V\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x12\r\n\x05stock\x18\x05 \x01(\x05\"\x1c\n\x0eProductRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"3\n\x0bProductList\x12$\n\x08products\x18\x01 \x03(\x0b\x32\x12.inventory.Product\"/\n\x0fProductResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\"\x07\n\x05\x45mpty2\xd2\x02\n\x10InventoryService\x12<\n\nAddProduct\x12\x12.inventory.Product\x1a\x1a.inventory.ProductResponse\x12;\n\nGetProduct\x12\x19.inventory.ProductRequest\x1a\x12.inventory.Product\x12:\n\x0eGetAllProducts\x12\x10.inventory.Empty\x1a\x16.inventory.ProductList\x12?\n\rUpdateProduct\x12\x12.inventory.Product\x1a\x1a.inventory.ProductResponse\x12\x46\n\rDeleteProduct\x12\x19.inventory.ProductRequest\x1a\x1a.inventory.ProductResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCT']._serialized_start=38
  _globals['_PRODUCT']._serialized_end=124
  _globals['_PRODUCTREQUEST']._serialized_start=126
  _globals['_PRODUCTREQUEST']._serialized_end=154
  _globals['_PRODUCTLIST']._serialized_start=156
  _globals['_PRODUCTLIST']._serialized_end=207
  _globals['_PRODUCTRESPONSE']._serialized_start=209
  _globals['_PRODUCTRESPONSE']._serialized_end=256
  _globals['_EMPTY']._serialized_start=258
  _globals['_EMPTY']._serialized_end=265
  _globals['_INVENTORYSERVICE']._serialized_start=268
  _globals['_INVENTORYSERVICE']._serialized_end=606
# @@protoc_insertion_point(module_scope)
